#spring:
#  datasource:
#    url: jdbc:sqlserver://139.9.80.186:1433;DatabaseName=KKSHUJU
#    username: sa
#    password: gdly$2020999
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#  thymeleaf:
#    cache: false
#
#server:
#  port: 9001
spring:
  datasource:
    url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=KKZTWL
    username: sa
    password: ~bellserver!1982
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  thymeleaf:
    cache: false

server:
  port: 9001

